<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Hangfire.Core" Version="1.8.23" />
    <PackageReference Include="MediatR" Version="12.5.0" />
	<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	<PackageReference Include="Scrutor" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Students\Commands\" />
    <Folder Include="Features\Students\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EduManager.Domain\EduManager.Domain.csproj" />
  </ItemGroup>

</Project>
